const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#5B8FCC",
    background: "#080D1A",
    foreground: "#FFFFFF",
    card: "#0F1A2E",
    cardForeground: "#FFFFFF",
    primary: "#5B8FCC",
    primaryForeground: "#FFFFFF",
    secondary: "#0D1525",
    secondaryForeground: "#94A3B8",
    muted: "#0D1525",
    mutedForeground: "#64748B",
    accent: "#1E293B",
    accentForeground: "#E2E8F0",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2535",
    input: "#1e2535",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#5B8FCC",
    background: "#080D1A",
    foreground: "#FFFFFF",
    card: "#0F1A2E",
    cardForeground: "#FFFFFF",
    primary: "#5B8FCC",
    primaryForeground: "#FFFFFF",
    secondary: "#0D1525",
    secondaryForeground: "#94A3B8",
    muted: "#0D1525",
    mutedForeground: "#64748B",
    accent: "#1E293B",
    accentForeground: "#E2E8F0",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2535",
    input: "#1e2535",
  },
  radius: 12,
};

export default colors;
